### PR TITLE
Develop screensaver

### PR DESCRIPTION
**Pull request by KalaRaja**
Issue - #15 

Description of changes - 
added screen saver 

@GagsdName 

TO-DO checklist before submitting your pull-request - 

- [x] Are all acceptance criteria met ?
- [ ] Has the code been documented properly ? N/A for now
- [x] Does component css-class structure conform to the Blue Dino style template i.e. top-level element .wrapper, .container and other inside css classes ?
- [x] Have all checks passed ?
- [x] Have you tested inter-browser functionality ? works on Edge, chrome and FF, not on IE

### CODE REVIEW

**Comment by KalaRaja** [comment]
The sonarcloud issue is not relevant. @gurjaspalbedi please add a rule to ignore it.

**Comment by bherr2** [comment]
> The sonarcloud issue is not relevant. @gurjaspalbedi please add a rule to ignore it.

I know its silly but it doesn't look that hard to make subtitle and description files for this.

See: 
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

The simplest possible VTT file is:
```webvtt
WEBVTT
```

**Comment by GagsdName** [comment]
@axdanbol Could you please review the test-cases.

**Comment by axdanbol** [comment]
The idle timer needs to be tested using `document.dispatchEvent` in the test cases

**Comment by GagsdName** [comment]
Looks good. Approving the changes, but please rename screen-saver-header.component to a more meaningful name.

**Pull request merged**
